apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cicd-tester.fullname" . | default .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cicd-tester
  template:
    metadata:
      labels:
        app: cicd-tester
    spec:
      containers:
        - name: api-tester
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
